(defpackage :lispi
  (:use :cl)
  (:export
   #:*tool-working-directory*
   #:*file-read-default-limit*
   #:*find-default-limit*
   #:*grep-default-limit*
   #:*grep-max-file-bytes*
   #:*grep-max-line-length*
   #:*search-ignored-directory-names*
   #:*diff-display-max-lines*
   #:*lisp-eval-default-package*
   #:*last-eval-result*
   #:*last-eval-condition*
   #:*lisp-eval-history*
   #:*lisp-eval-history-limit*
   #:*lisp-eval-max-output-chars*
   #:lisp-eval-record
   #:lisp-eval-record-code
   #:lisp-eval-record-package
   #:lisp-eval-record-result
   #:lisp-eval-record-output
   #:lisp-eval-record-error-output
   #:lisp-eval-record-condition
   #:lisp-eval-record-timestamp
   #:lisp-data-string
   #:lisp-data-read
   #:tool-error-result-data
   #:tool-key-name
   #:tool-key=
   #:tool-plist-p
   #:tool-args-alist
   #:tool-arg
   #:compute-simple-diff
   #:tool-working-directory-pathname
   #:resolve-tool-path
   #:execute-read
   #:execute-find
   #:execute-grep
   #:execute-write
   #:execute-edit
   #:execute-lisp-eval
   #:eval-history-to-string
   #:default-tool-specs))
