(defpackage #:clawmacs/matching-core
  (:use #:cl)
  (:export
   #:split-query-tokens
   #:fuzzy-token-match-p
   #:fuzzy-match-p
   #:fuzzy-token-positions
   #:fuzzy-match-positions
   #:fuzzy-token-score-or-negative-one
   #:fuzzy-score-or-negative-one))

(defpackage :clawmacs
  (:use :cl)
  (:shadowing-import-from :lispi
   #:*sandbox-root*
   #:*file-read-default-limit*
   #:*find-default-limit*
   #:*grep-default-limit*
   #:*grep-max-file-bytes*
   #:*grep-max-line-length*
   #:*search-ignored-directory-names*
   #:*diff-display-max-lines*
   #:*lisp-eval-default-package*
   #:*last-eval-result*
   #:*last-eval-condition*
   #:*lisp-eval-history*
   #:*lisp-eval-history-limit*
   #:*lisp-eval-max-output-chars*
   #:lisp-eval-record
   #:lisp-eval-record-code
   #:lisp-eval-record-package
   #:lisp-eval-record-result
   #:lisp-eval-record-output
   #:lisp-eval-record-error-output
   #:lisp-eval-record-condition
   #:lisp-eval-record-timestamp
   #:lisp-data-string
   #:lisp-data-read
   #:tool-error-result-data
   #:tool-denied-result-data
   #:tool-key-name
   #:tool-key=
   #:tool-plist-p
   #:tool-args-alist
   #:tool-arg
   #:compute-simple-diff
   #:validate-sandbox-path
   #:execute-read
   #:execute-find
   #:execute-grep
   #:execute-write
   #:execute-edit
   #:execute-lisp-eval
   #:file-write-approval-display
   #:file-edit-approval-display
   #:eval-history-to-string)
  (:export
   ;; General utilities
   #:count-occurrences

   ;; Legacy color specs
   #:color-spec
   #:make-color-spec
   #:color-spec-type
   #:color-spec-value

   ;; CLIM drawing styles
   #:make-cga-ink
   #:make-256-color-ink
   #:make-hex-ink
   #:make-clim-ink
   #:make-clim-text-style
   #:default-clawmacs-text-style
   #:bold-clawmacs-text-style
   #:drawing-style
   #:make-drawing-style
   #:drawing-style-name
   #:drawing-style-ink
   #:drawing-style-background-ink
   #:drawing-style-text-style
   #:drawing-style-drawing-options
   #:drawing-style-underline-p
   #:drawing-style-parent
   #:drawing-style-transform
   #:resolved-drawing-style
   #:resolved-drawing-style-ink
   #:resolved-drawing-style-background-ink
   #:resolved-drawing-style-text-style
   #:resolved-drawing-style-drawing-options
   #:resolved-drawing-style-underline-p
   #:resolve-drawing-style

   ;; Legacy faces
   #:face
   #:face-name
   #:face-foreground
   #:face-background
   #:face-bold-p
   #:face-underline-p
   #:face-reverse-p
   #:face-parent
   #:face-transform
   #:resolved-face
   #:resolved-face-foreground
   #:resolved-face-background
   #:resolved-face-bold-p
   #:resolved-face-underline-p
   #:resolved-face-reverse-p
   #:resolved-face-text-style
   #:resolved-face-drawing-options
   #:resolve-face

   ;; Drawing style sets / legacy face sets
   #:drawing-style-set
   #:drawing-style-set-owner
   #:drawing-style-set-styles
   #:make-drawing-style-set
   #:get-drawing-style
   #:face-set
   #:face-set-owner
   #:face-set-faces
   #:make-face-set
   #:get-face

   ;; Global face registry
   #:*global-face-registry*
   #:global-face
   #:init-global-faces
   #:collect-global-faces
   #:make-default-system-face-set
   #:make-default-compaction-summary-face-set
   #:make-default-text-face
   #:init-face-registry
   #:ensure-buffer-agent-face-set

   ;; Lines
   #:line
   #:make-line
   #:line-content
   #:line-next
   #:line-prev

   ;; Messages
   #:message
   #:make-message
   #:message-first-line
   #:message-last-line
   #:message-point-line
   #:message-point-offset
   #:message-mark-line
   #:message-mark-offset
   #:message-sender
   #:message-timestamp
   #:message-face-set
   #:message-read-only-p
   #:message-next
   #:message-prev
   #:message-raw-content
   #:message-metadata
   #:message-entry-id
   #:message-parent-entry-id
   #:message-text
   #:message-line-count

   ;; Sessions
   #:*sessions-dir*
   #:session
   #:session-name
   #:session-id
   #:session-directory
   #:session-manifest-path
   #:session-transcript-directory
   #:session-current-transcript-index
   #:session-current-transcript-path
   #:session-current-leaf-id
   #:session-parent-session
   #:session-working-directory
   #:session-tree-node
   #:session-tree-node-entry
   #:session-tree-node-label
   #:session-tree-node-children
   #:session-normalized-tree-events
   #:session-tree-roots
   #:session-active-path-ids
   #:session-active-branch-message-events
   #:session-branch-state
   #:session-effective-leaf-id
   #:session-find-entry
   #:session-navigation-leaf-for-entry
   #:session-entry-user-message-text
   #:set-session-current-leaf
   #:record-session-compaction
   #:record-session-branch-summary
   #:record-session-label-change
   #:record-session-model-change
   #:record-session-think-level-change
   #:create-branched-session
   #:load-or-create-session
   #:record-session-message
   #:rotate-session-transcript

   ;; Message editing
   #:message-insert-char
   #:message-insert-newline
   #:set-message-text
   #:message-delete-char-backward
   #:message-delete-char-forward
   #:message-forward-char
   #:message-backward-char
   #:message-forward-word
   #:message-backward-word
   #:message-forward-line
   #:message-backward-line
   #:message-beginning-of-buffer
   #:message-end-of-buffer
   #:message-point-absolute-offset
   #:set-message-point-from-absolute-offset
   #:message-mark-active-p
   #:message-mark-absolute-offset
   #:message-set-mark-at-point
   #:message-clear-mark
   #:message-region-bounds
   #:message-region-text
   #:message-delete-region
   #:message-kill-region
   #:message-copy-region
   #:message-exchange-point-and-mark
   #:message-mark-whole-buffer
   #:message-current-line-number
   #:message-current-column-number
   #:message-search-forward
   #:message-search-backward
   #:message-move-beginning-of-line
   #:message-move-end-of-line
   #:message-kill-line
   #:message-kill-backward-line
   #:message-kill-word
   #:message-backward-kill-word
   #:message-yank
   #:message-yank-pop

   ;; Kill ring
   #:*kill-ring*
   #:kill-ring-push
   #:kill-ring-top

   ;; Buffer
   #:*default-context-limit*
   #:*default-agent-name*
   #:*default-show-tool-results*
   #:*default-show-reasoning-output*
   #:*default-show-metadata-output*
   #:*default-pipeline-name*
   #:*scratch-buffer-name*
   #:*scratch-buffer-initial-text*
   #:*listener-buffer-name*
   #:buffer
   #:make-buffer
   #:buffer-type
   #:make-buffer-type
   #:buffer-type-name
   #:buffer-type-description
   #:buffer-type-major-mode
   #:buffer-type-document-p
   #:buffer-type-presentation-function
   #:buffer-type-input-presentation-function
   #:buffer-type-serialize-state-function
   #:buffer-type-restore-state-function
   #:buffer-type-package
   #:register-buffer-type
   #:define-buffer-type
   #:find-buffer-type
   #:list-buffer-types
   #:buffer-type-for-buffer
   #:buffer-presentation-function
   #:buffer-input-presentation-function
   #:buffer-name
   #:buffer-first-message
   #:buffer-last-message
   #:buffer-input-message
   #:buffer-agent-name
   #:buffer-kind
   #:buffer-working-directory
   #:buffer-project-name
   #:buffer-resource-path
   #:buffer-original-text
   #:buffer-dirty-p
   #:buffer-token-count
   #:buffer-context-limit
   #:buffer-status
   #:buffer-provider-override
   #:buffer-model-override
   #:buffer-think-level-override
   #:buffer-pipeline-name
   #:buffer-enabled-packages
   #:buffer-session
   #:set-buffer-provider-override
   #:set-buffer-model-override
   #:set-buffer-think-level-override
   #:clear-buffer-provider-override
   #:clear-buffer-model-override
   #:clear-buffer-think-level-override
   #:clear-buffer-routing-overrides
   #:set-buffer-pipeline
   #:clear-buffer-pipeline
   #:buffer-face-registry
   #:buffer-keymap
   #:buffer-scroll-offset
   #:buffer-show-tool-results-p
   #:buffer-show-reasoning-p
   #:buffer-show-metadata-p
   #:buffer-pending-stream
   #:buffer-streaming-message
   #:*buffer-ring*
   #:current-buffer
   #:add-buffer-to-ring
   #:switch-to-buffer
   #:kill-buffer-from-ring
   #:find-buffer-by-name
   #:scratch-buffer-p
   #:file-buffer-p
   #:listener-buffer-p
   #:document-buffer-p
   #:buffer-llm-running-p
   #:make-chat-buffer
   #:scratch-buffer
   #:ensure-scratch-buffer
   #:scratch-buffer-text
   #:file-buffer-text
   #:ensure-file-keymap-initialized
   #:file-buffer-dirty-p
   #:mark-buffer-dirty
   #:next-buffer-name
   #:buffer-names
   #:buffer-finalize-input

   ;; Listener buffers
   #:listener-state
   #:make-listener-state
   #:listener-state-package-name
   #:listener-state-directory-stack
   #:listener-state-last-values
   #:listener-state-command-history
   #:listener-buffer-state
   #:listener-prompt-text
   #:listener-wholine-text
   #:listener-command-help-text
   #:make-listener-buffer
   #:ensure-listener-buffer
   #:submit-listener-input
   #:buffer-clear-history-before-input
   #:buffer-insert-read-only-message
   #:buffer-insert-agent-message
   #:buffer-insert-system-message
   #:buffer-insert-context-message
   #:notify-buffer-display-change
   #:buffer-message-count
   #:save-session
   #:replace-buffer-history-with-serialized-messages
   #:load-session
   #:list-saved-sessions

   ;; Windows
   #:clawmacs-window
   #:make-clawmacs-window
   #:clawmacs-window-id
   #:clawmacs-window-buffer
   #:clawmacs-window-node
   #:clawmacs-window-node-kind
   #:clawmacs-window-node-window
   #:clawmacs-window-node-orientation
   #:clawmacs-window-node-first
   #:clawmacs-window-node-second
   #:make-clawmacs-window-tree
   #:make-clawmacs-window-leaf
   #:make-clawmacs-window-split
   #:clawmacs-window-node-leaf-p
   #:clawmacs-window-node-split-p
   #:clawmacs-window-tree-windows
   #:clawmacs-window-tree-count
   #:clawmacs-window-tree-find-window
   #:clawmacs-window-tree-find-node
   #:split-clawmacs-window-tree
   #:clawmacs-window-tree-next-window
   #:delete-clawmacs-window-from-tree
   #:delete-other-clawmacs-windows
   #:clawmacs-window-tree-replace-dead-buffers
   #:clawmacs-window-layout-entry
   #:clawmacs-window-layout-entry-window
   #:clawmacs-window-layout-entry-row
   #:clawmacs-window-layout-entry-col
   #:clawmacs-window-layout-entry-rows
   #:clawmacs-window-layout-entry-cols
   #:clawmacs-window-separator
   #:clawmacs-window-separator-orientation
   #:clawmacs-window-separator-row
   #:clawmacs-window-separator-col
   #:clawmacs-window-separator-rows
   #:clawmacs-window-separator-cols
   #:clawmacs-window-tree-layout

   ;; Commands
   #:*current-caller*
   #:*sandbox-root*
   #:*command-table*
   #:command-metadata
   #:command-metadata-name
   #:command-metadata-docstring
   #:command-metadata-keybindings
   #:command-metadata-lambda-list
   #:command-metadata-prompts
   #:command-metadata-package
   #:defcommand
   #:list-available-commands
   #:command-required-arguments
   #:resolve-command-prompt-reader

   ;; Extended documentation
   #:*extended-docs*
   #:defdoc
   #:extended-doc
   #:deftool
   #:agent-tool-metadata
   #:agent-tool-metadata-symbol
   #:agent-tool-metadata-name
   #:agent-tool-metadata-description
   #:agent-tool-metadata-args
   #:agent-tool-metadata-input-schema
   #:agent-tool-metadata-permission
   #:agent-tool-metadata-call-style
   #:agent-tool-metadata-approval-display-fn
   #:agent-tool-metadata-command-p
   #:agent-tool-metadata-lambda-list
   #:agent-tool-metadata-package
   #:register-agent-tool-metadata
   #:unregister-agent-tool-metadata
   #:find-agent-tool-metadata
   #:list-agent-tool-metadata
   #:undocumented-functions
   #:undocumented-variables

   ;; Keymaps
   #:keymap
   #:make-keymap
   #:keymap-name
   #:keymap-bindings
   #:keymap-parent
   #:keymap-bind
   #:keymap-lookup
   #:*default-keymap*
   #:*file-keymap*
   #:*alt-emulates-meta*

   ;; Projects
   #:project
   #:make-project
   #:project-name
   #:project-root
   #:project-description
   #:project-source
   #:project-systems
   #:project-check-functions
   #:project-reload-function
   #:change-set
   #:make-change-set
   #:change-set-id
   #:change-set-name
   #:change-set-description
   #:change-set-entries
   #:change-set-status
   #:change-set-created-at
   #:change-set-applied-at
   #:change-set-entry
   #:change-set-entry-kind
   #:change-set-entry-project-name
   #:change-set-entry-path
   #:change-set-entry-new-path
   #:change-set-entry-new-text
   #:change-set-entry-old-exists-p
   #:change-set-entry-old-text
   #:change-set-entry-target-old-exists-p
   #:change-set-entry-target-old-text
   #:change-set-entry-applied-p
   #:*project-definitions-directory*
   #:*project-registry*
   #:*project-manifest-extension*
   #:*project-ignored-directory-names*
   #:*project-list-file-limit*
   #:*project-search-result-limit*
   #:*change-set-registry*
   #:*current-change-set*
   #:define-project
   #:create-project
   #:register-project
   #:find-project
   #:list-projects
   #:load-project-definitions
   #:reload-projects
   #:project-resolve-path
   #:project-list-files
   #:project-read-file
   #:project-create-file
   #:project-save-file
   #:project-search
   #:project-search-to-string
   #:project-open-file
   #:find-project-file-buffer
   #:project-save-buffer
   #:begin-change-set
   #:current-change-set
   #:find-change-set
   #:list-change-sets
   #:stage-project-file
   #:stage-project-delete
   #:stage-project-rename
   #:change-set-project-file-text
   #:change-set-diff-to-string
   #:change-set-summary-to-string
   #:apply-change-set
   #:discard-change-set
   #:revert-change-set
   #:run-project-checks
   #:compile-project-file
   #:load-project-file
   #:reload-project-system
   #:project-outline-to-string
   #:project-find-definitions
   #:project-find-definitions-to-string
   #:project-find-references-to-string
   #:project-package-map-to-string
   #:project-describe-definition-to-string

   ;; Skills
   #:skill
   #:make-skill
   #:skill-name
   #:skill-description
   #:skill-short-description
   #:skill-display-name
   #:skill-interface-short-description
   #:skill-default-prompt
   #:skill-icon-small
   #:skill-icon-large
   #:skill-brand-color
   #:skill-allow-implicit-invocation-p
   #:skill-path
   #:skill-root
   #:skill-scope
   #:skill-source
   #:skill-contents
   #:skill-root-definition
   #:make-skill-root
   #:skill-root-path
   #:skill-root-scope
   #:skill-root-source
   #:skill-error
   #:make-skill-error
   #:skill-error-path
   #:skill-error-message
   #:skill-load-outcome
   #:skill-load-outcome-skills
   #:skill-load-outcome-errors
   #:skill-load-outcome-disabled-paths
   #:*skill-user-directory*
   #:*skill-agents-directory*
   #:*skill-system-directory*
   #:*skill-configuration-path*
   #:*skill-roots*
   #:*programmatic-skills*
   #:*skill-scan-max-depth*
   #:*skill-scan-max-directories-per-root*
   #:*skill-list-file-limit*
   #:*skill-search-result-limit*
   #:register-skill-root
   #:register-skill-definition
   #:reload-skills
   #:clear-skills-cache
   #:ensure-skills-loaded
   #:list-skills
   #:list-skill-errors
   #:list-skills-to-string
   #:find-skill
   #:skill-enabled-p
   #:set-skill-enabled
   #:enable-skill
   #:disable-skill
   #:save-skill-configuration
   #:read-skill-instructions
   #:skill-list-files
   #:skill-read-file
   #:skill-search-to-string
   #:describe-skill-to-string
   #:collect-skill-mentions
   #:skill-injection-messages
   #:render-skills-section

   ;; Prompt templates and slash commands
   #:prompt-template
   #:make-prompt-template
   #:prompt-template-name
   #:prompt-template-description
   #:prompt-template-body
   #:prompt-template-path
   #:prompt-template-scope
   #:prompt-template-package
   #:slash-command
   #:make-slash-command
   #:slash-command-name
   #:slash-command-description
   #:slash-command-argument-hint
   #:slash-command-handler
   #:slash-command-package
   #:*slash-command-table*
   #:register-slash-command
   #:list-slash-commands
   #:find-slash-command
   #:parse-slash-command-line
   #:parse-prompt-template-markdown
   #:discover-prompt-templates-in-directory
   #:expand-prompt-template-body
   #:process-slash-command

    ;; LLM
    #:*zai-env-var*
    #:read-env-token
    #:provider-token-path
    #:read-provider-token
    #:save-provider-token
     #:agent-definition
     #:make-agent-definition
     #:agent-definition-name
     #:agent-definition-provider
     #:agent-definition-model
     #:agent-definition-think-level
     #:agent-definition-core-prompt
     #:agent-definition-personality-prompt
     #:agent-definition-tool-names
     #:register-agent-definition
     #:find-agent-definition
     #:list-agent-definitions
     #:load-agent-defaults
     #:save-agent-defaults
     #:agent-default
     #:set-agent-default
     #:ensure-agent-defaults-loaded
     #:resolve-buffer-provider-and-model
     #:build-agent-system-prompt
     #:*default-core-system-prompt*
     #:*default-personality-prompt*
     #:*personality-prompt-path*
     #:load-personality-prompt-file
     #:provider-model-supported-think-levels
     #:reconcile-buffer-think-level-override
     #:*boot-file-names*
     #:load-boot-files
     #:*agent-defaults-path*
     #:build-conversation-messages
   #:*default-provider*
   #:*default-model*
   #:*default-max-tokens*
   #:*openai-codex-reasoning-summary*
   #:api-json-encode
   #:api-json-decode

   ;; Compaction
   #:*compaction-point*
   #:*compaction-function*
   #:*compaction-prompt*
   #:*compaction-summary-prefix*
   #:*compaction-preserved-user-message-token-limit*
   #:buffer-conversation-token-estimate
   #:compaction-threshold-tokens
   #:compaction-needed-p
   #:maybe-compact-buffer
   #:default-compact-buffer
   #:compact-buffer-command

   ;; Z.AI (Zhipu AI)
   #:*zai-model*
   #:*zai-api-url*
   #:zai-request
   #:zai-request-streaming

   ;; OpenRouter
   #:*openrouter-model*
   #:*openrouter-api-url*
   #:*openrouter-models-url*
   #:*openrouter-env-var*
   #:*openrouter-cached-models*
   #:fetch-openrouter-models
   #:openrouter-request
   #:openrouter-request-streaming

   ;; OpenAI Codex OAuth
   #:*openai-oauth-client-id*
   #:*openai-oauth-auth-url*
   #:*openai-oauth-token-url*
   #:*openai-oauth-redirect-uri*
   #:*openai-oauth-scopes*
   #:*codex-auth-path*
   #:generate-code-verifier
   #:compute-code-challenge
   #:generate-oauth-state
   #:url-encode-param
   #:extract-oauth-callback-params
   #:openai-codex-oauth-start
   #:exchange-openai-oauth-code
   #:save-openai-codex-oauth-tokens
   #:read-openai-codex-oauth-tokens
   #:refresh-openai-codex-oauth-token
   #:read-openai-codex-oauth-token
   #:openai-codex-oauth-finish
   #:*openai-oauth-pending*
   #:openai-codex-oauth-command

   ;; Tools
   #:*http-fetch-max-chars*
   #:*http-connection-timeout*
   #:*http-user-agent*
   #:*file-read-default-limit*
   #:*find-default-limit*
   #:*grep-default-limit*
   #:*grep-max-file-bytes*
   #:*grep-max-line-length*
   #:*search-ignored-directory-names*
   #:*shell-exec-default-timeout*
   #:*diff-display-max-lines*
   #:*lisp-eval-default-package*
   #:*last-eval-result*
   #:*last-eval-condition*
   #:*lisp-eval-history*
   #:*lisp-eval-history-limit*
   #:*lisp-eval-max-output-chars*
   #:*tool-table*
   #:*active-tool-names*
   #:*temporary-tool-table*
   #:*current-tool-buffer*
   #:lisp-eval-record
   #:lisp-eval-record-code
   #:lisp-eval-record-package
   #:lisp-eval-record-result
   #:lisp-eval-record-output
   #:lisp-eval-record-error-output
   #:lisp-eval-record-condition
   #:lisp-eval-record-timestamp
   #:tool-definition
   #:tool-definition-name
   #:tool-definition-description
   #:tool-definition-input-schema
   #:tool-definition-permission
   #:tool-definition-execute-fn
   #:tool-definition-approval-display-fn
   #:tool-definition-package
   #:subagent-tool
   #:subagent-tool-name
   #:subagent-tool-description
   #:subagent-tool-input-schema
   #:subagent-tool-permission
   #:subagent-tool-execute-fn
   #:subagent-tool-approval-display-fn
   #:make-subagent-tool
   #:register-tool
   #:execute-tool
   #:tool-requires-permission-p
   #:tool-definitions-for-api
   #:render-agent-tools-section
   #:format-tool-call-sexpr
   #:format-tool-call-expanded
   #:tool-approval-extra-display
   #:eval-history-to-string
   #:init-tools

   ;; Standard reference / library discovery
   #:*common-lisp-spec-root*
   #:common-lisp-spec-available-p
   #:find-common-lisp-spec-entry
   #:describe-common-lisp-symbol-to-string
   #:search-common-lisp-spec-to-string
   #:list-project-systems
   #:describe-system-to-string
   #:list-system-packages
   #:list-package-functions
   #:list-package-variables
   #:list-package-types
   #:describe-library-symbol-to-string
   #:search-system-docs

   ;; Sexed structural editing
   #:sexed-balanced-p
   #:balanced-parentheses-p
   #:sexed-diagnostics
   #:sexed-find-forms
   #:sexed-form-text
   #:sexed-outline-to-string
   #:sexed-replace-form
   #:sexed-delete-form
   #:sexed-insert-before-form
   #:sexed-insert-after-form
   #:sexed-insert-form-before
   #:sexed-insert-form-after
   #:sexed-wrap-form
   #:sexed-splice-form
   #:sexed-raise-form
   #:sexed-slurp-forward
   #:sexed-barf-forward
   #:sexed-read-file-text
   #:sexed-write-file-text
   #:sexed-file-outline-to-string
   #:sexed-file-form-text
   #:sexed-replace-file-form
   #:sexed-delete-file-form
   #:sexed-insert-before-file-form
   #:sexed-insert-after-file-form
   #:sexed-insert-file-form-before
   #:sexed-insert-file-form-after
   #:sexed-wrap-file-form
   #:sexed-splice-file-form
   #:sexed-raise-file-form
   #:sexed-slurp-forward-file-form
   #:sexed-barf-forward-file-form
   #:sexed-write-project-file-text
   #:sexed-project-outline-to-string
   #:sexed-project-form-text
   #:sexed-replace-project-form
   #:sexed-delete-project-form
   #:sexed-insert-before-project-form
   #:sexed-insert-after-project-form
   #:sexed-insert-project-form-before
   #:sexed-insert-project-form-after
   #:sexed-wrap-project-form
   #:sexed-splice-project-form
   #:sexed-raise-project-form
   #:sexed-slurp-forward-project-form
   #:sexed-barf-forward-project-form

   ;; Slop symbol intelligence
   #:*slop-default-result-limit*
   #:*slop-project-index-cache*
   #:slop-list-projects
   #:slop-current-project
   #:slop-index-project
   #:slop-project-symbols
   #:slop-symbol-at
   #:slop-find-definitions
   #:slop-find-definitions-batch
   #:slop-find-references
   #:slop-find-callers
   #:slop-find-callees
   #:slop-trace-calls
   #:slop-find-mentions
   #:slop-definition-context
   #:slop-find-variable-uses
   #:slop-rename-variable

   ;; Approval
   #:buffer-approval-pending
   #:buffer-approval-result
   #:buffer-stashed-input
   #:buffer-pending-tool-calls
   #:buffer-tool-call-results

   ;; Rendering
   #:resolve-modeline-provider-model

   ;; Buffer selector
   #:*buffer-selector-active*
   #:*buffer-selector-index*
   #:*session-tree-selector-active*
   #:*session-tree-selector-buffer*
   #:*session-tree-selector-items*
   #:*session-tree-selector-filtered-items*
   #:*session-tree-selector-index*
   #:*session-tree-selector-scroll*
   #:*session-tree-selector-search*
   #:*session-tree-selector-filter-mode*
   #:*session-tree-selector-folded-ids*
   #:session-tree-selector-activate
   #:session-tree-selector-deactivate
   #:session-tree-selector-update-filter
   #:session-tree-selector-current-item
   #:handle-session-tree-selector-key
   #:session-tree-command
   #:fork-session-command
   #:list-buffers-command
   #:split-window-below-command
   #:split-window-right-command
   #:delete-window-command
   #:delete-other-windows-command
   #:other-window-command
   #:minibuffer-select-project-command
   #:open-project-file-command
   #:create-project-file-command
   #:search-project-command
   #:insert-tab-command
   #:next-line-command
   #:previous-line-command
   #:beginning-of-buffer-command
   #:end-of-buffer-command
   #:set-mark-command
   #:keyboard-quit-command
   #:kill-region-command
   #:copy-region-command
   #:exchange-point-and-mark-command
   #:mark-whole-buffer-command
   #:search-forward-command
   #:search-backward-command
   #:revert-file-buffer-command
   #:write-project-file-as-command
   #:insert-file-command
   #:minibuffer-insert-skill-command
   #:minibuffer-toggle-skill-command
   #:list-skills-command
   #:minibuffer-toggle-package-command
   #:describe-installed-package-command

   ;; Model selector (overlay)
   #:*model-selector-active*
   #:*model-selector-index*
   #:*model-selector-entries*
   #:select-model-command
   #:handle-model-selector-key
   #:*think-selector-active*
   #:*think-selector-index*
   #:*think-selector-entries*
   #:select-think-level-command
   #:handle-think-selector-key

   ;; Minibuffer
   #:*minibuffer-active*
   #:*minibuffer-mode*
   #:*minibuffer-prompt*
   #:*minibuffer-input*
   #:*minibuffer-point*
   #:*minibuffer-items*
   #:*minibuffer-filtered-items*
   #:*minibuffer-selected-index*
   #:*minibuffer-scroll-offset*
   #:*minibuffer-match-positions*
   #:*minibuffer-callback*
   #:*minibuffer-max-height*
   #:*automatic-skill-completion-enabled*
   #:*skill-completion-enabled-buffer-kinds*
   #:*skill-completion-max-height*
   #:*model-selection-history*
   #:matching-core-available-p
   #:split-query-tokens
   #:fuzzy-token-match-p
   #:fuzzy-token-positions
   #:fuzzy-match-positions
   #:fuzzy-token-score
   #:fuzzy-score
   #:fuzzy-match-p
   #:minibuffer-item-display
   #:minibuffer-item-match-text
   #:minibuffer-activate
   #:minibuffer-prompt
   #:minibuffer-deactivate
   #:minibuffer-update-filter
   #:minibuffer-visible-item-count
   #:minibuffer-ensure-visible
   #:minibuffer-confirm
   #:minibuffer-cancel
   #:handle-minibuffer-key
   #:sort-models-by-recency
   #:*buffer-selection-history*
   #:sort-buffers-by-recency
   #:minibuffer-current-height
   #:invoke-command
   #:execute-extended-command
   #:minibuffer-select-agent-command
   #:minibuffer-select-model-command
   #:minibuffer-select-think-level-command
   #:minibuffer-select-buffer-command
   #:load-session-command
   #:new-listener-buffer-command
   #:help-buffer-p
   #:customize-buffer-p
   #:help-buffer-text

   ;; Introspection / Help
   #:list-functions
   #:find-keybindings-for-command
   #:format-key-binding
   #:format-session-tree-selector-line
   #:describe-function-to-string
   #:make-help-buffer
   #:describe-function-command
   #:buffer-major-mode
   #:list-variables
   #:variable-kind
   #:truncate-value-string
   #:describe-variable-to-string
   #:describe-variable-command

   ;; Describe bindings
   #:*ch-pending*
   #:categorize-command
   #:describe-bindings-to-string
   #:describe-bindings-command

   ;; Customize face
   #:*customize-face-state*
   #:*customize-face-fields*
   #:cga-color-name
   #:format-color-spec-display
   #:format-clim-ink-display
   #:format-clim-text-style-display
   #:format-drawing-options-display
   #:format-boolean-display
   #:format-face-parent-display
   #:customize-face-field-value
   #:customize-face-set-field-value
   #:customize-face-field-label
   #:customize-face-field-display
   #:customize-face-snapshot
   #:customize-face-restore-snapshot
   #:build-customize-face-content
   #:rebuild-customize-face-display
   #:customize-face-next-field
   #:customize-face-prev-field
   #:customize-face-toggle-field
   #:collect-all-faces
   #:make-color-selection-items
   #:make-text-style-selection-items
   #:make-drawing-options-selection-items
   #:make-boolean-selection-items
   #:make-parent-selection-items
   #:customize-face-edit-field
   #:customize-face-apply
   #:customize-face-cancel
   #:customize-face-revert-to-original
   #:make-customize-face-buffer
   #:handle-customize-key
   #:customize-drawing-style-command
   #:customize-face-command

   ;; Type introspection
   #:list-types
   #:type-kind
   #:type-kind-label
   #:type-slot-info
   #:type-struct-slot-info
   #:describe-type-to-string
   #:undocumented-types
   #:describe-type-command

   ;; Known models
   #:*provider-known-models*
   #:provider-known-models
   #:provider-has-token-p
   #:available-models-for-selector

   ;; Prefix processing
   #:*prefix-handlers*
   #:find-prefix-handler
   #:process-prefix-command
   #:shell-prefix-handler

   ;; Debug mode
   #:*debug-mode*
   #:*debug-log-file*
   #:debug-log
   #:file-debug-log
   #:*mcclim-debugger-enabled*
   #:*mcclim-listener-debugger-enabled*
   #:*mcclim-debug-inspector-frames*
   #:*clouseau-extensions-installed-p*
   #:*clouseau-extension-classes*
   #:mcclim-debug-feature-status
   #:mcclim-debug-status-to-string
   #:mcclim-debug-snapshot-to-string
   #:ensure-clouseau-support
   #:clouseau-status-to-string
   #:clouseau-inspector-entries
   #:clouseau-inspectors-to-string
   #:clouseau-update-inspector-root
   #:clouseau-application-state
   #:mcclim-install-debugger
   #:mcclim-disable-debugger
   #:mcclim-launch-listener
   #:mcclim-debug-inspect-target
   #:mcclim-debug-inspect-lisp-form
   #:mcclim-refresh-inspectors
   #:toggle-debug-mode-command
   #:mcclim-debug-status-command
   #:mcclim-debug-snapshot-command
   #:mcclim-install-debugger-command
   #:mcclim-disable-debugger-command
   #:mcclim-launch-listener-command
   #:mcclim-toggle-listener-debugger-command
   #:mcclim-inspect-current-frame-command
   #:mcclim-inspect-visible-buffer-command
   #:mcclim-inspect-current-buffer-command
   #:mcclim-inspect-window-tree-command
   #:mcclim-inspect-selected-window-command
   #:mcclim-inspect-main-pane-command
   #:mcclim-inspect-input-pane-command
   #:mcclim-inspect-render-snapshot-command
   #:mcclim-inspect-debug-status-command
   #:mcclim-inspect-lisp-form-command
   #:mcclim-refresh-inspectors-command
   #:clouseau-status-command
   #:clouseau-install-extensions-command
   #:clouseau-list-inspectors-command
   #:clouseau-refresh-inspectors-command
   #:clouseau-inspect-application-state-command
   #:clouseau-inspect-buffer-ring-command
   #:clouseau-inspect-current-session-command
   #:clouseau-inspect-input-message-command
   #:clouseau-inspect-package-registry-command
   #:clouseau-inspect-tool-registry-command
   #:clouseau-inspect-pipeline-registry-command
   #:clouseau-set-inspector-root-command
   #:toggle-reasoning-output-command
   #:toggle-metadata-output-command
   #:redraw-screen-command

   ;; Package loader
   #:package-channel
   #:make-package-channel
   #:package-channel-name
   #:package-channel-root
   #:package-channel-description
   #:package-channel-source
   #:package-definition
   #:make-package-definition
   #:package-definition-name
   #:package-definition-description
   #:package-definition-root
   #:package-definition-entrypoint
   #:package-definition-channel
   #:package-definition-source-tier
   #:package-definition-autoload
   #:package-definition-dependencies
   #:package-definition-system-prompt-section
   #:package-definition-prompt-template-directory
   #:package-definition-slash-commands
   #:package-slash-command-spec
   #:make-package-slash-command-spec
   #:package-slash-command-spec-name
   #:package-slash-command-spec-description
   #:package-slash-command-spec-argument-hint
   #:package-slash-command-spec-handler
   #:package-prompt-section
   #:make-package-prompt-section
   #:package-prompt-section-name
   #:package-prompt-section-title
   #:package-prompt-section-package
   #:package-prompt-section-body
   #:*default-package-channel-directory*
   #:*package-channels*
   #:*enabled-builtin-packages*
   #:*package-configuration-path*
   #:*packages-directory*
   #:*current-clawmacs-package*
   #:register-package-channel
   #:list-package-channels
   #:reload-package-channels
   #:list-available-packages
   #:find-available-package
   #:list-installed-packages
   #:find-installed-package
   #:package-enablement-scope
   #:set-package-enablement-scope
   #:cycle-package-enablement-scope
   #:active-package-names
   #:package-display-description
   #:package-scope-label
   #:package-scope-message
   #:package-owned-command-metadata
   #:package-owned-tool-metadata
   #:package-owned-prompt-sections
   #:package-owned-buffer-types
   #:package-system-prompt-context-text
   #:maybe-insert-enabled-package-context
   #:describe-installed-package-to-string
   #:load-clawmacs-package
   #:load-active-packages
   #:reload-active-packages
   #:load-autoload-packages
   #:register-package-prompt-section
   #:list-package-prompt-sections
   #:render-package-prompt-sections
   #:clawmacs-use-package

   ;; User init
   #:*user-init-directory*
   #:*user-init-file*
   #:*inhibit-user-init*
   #:hook-metadata
   #:hook-metadata-name
   #:hook-metadata-args
   #:hook-metadata-docstring
   #:defhook
   #:find-hook-metadata
   #:list-hooks
   #:*startup-hook*
   #:*initial-buffer-hook*
   #:*before-command-hook*
   #:*after-command-hook*
   #:*before-tool-hook*
   #:*after-tool-hook*
   #:*before-send-message-hook*
   #:*after-send-message-hook*
   #:*after-buffer-create-hook*
   #:*after-message-insert-hook*
   #:*after-buffer-display-change-hook*
   #:*after-provider-response-hook*
   #:*package-enablement-changed-hook*
   #:*after-session-save-hook*
   #:*after-session-load-hook*
   #:add-hook
   #:remove-hook
   #:run-hooks
   #:run-hook-with-args
   #:advice-entry
   #:advice-entry-name
   #:advice-entry-where
   #:advice-entry-designator
   #:add-advice
   #:remove-advice
   #:advice-member-p
   #:list-advices
   #:clear-advices
   #:defadvice
   #:load-user-init-file

   ;; McCLIM presentation types
   #:chat-message
   #:tool-call
   #:buffer-ref
   #:clawmacs-window-ref
   #:model-ref

   ;; Main
   #:clawmacs-main
   #:run-clawmacs-mcclim
   #:clawmacs-prompt-main
   #:clawmacs-session-prompt-main
   #:run-single-prompt
   #:run-session-prompt
   #:pipeline-stage
   #:make-pipeline-stage
   #:pipeline-stage-name
   #:pipeline-stage-agent-name
   #:pipeline-stage-prompt
   #:pipeline-stage-next
   #:pipeline-stage-provider
   #:pipeline-stage-model
   #:pipeline-stage-think-level
   #:pipeline-stage-tool-names
   #:pipeline-stage-tool-names-supplied-p
   #:pipeline-stage-package-names
   #:pipeline-stage-skill-names
   #:pipeline-stage-max-tool-iterations
   #:pipeline-stage-auto-approve-tools-p
   #:pipeline-stage-output-parser
   #:pipeline-stage-runner
   #:pipeline-definition
   #:make-pipeline-definition
   #:pipeline-definition-name
   #:pipeline-definition-description
   #:pipeline-definition-stages
   #:pipeline-definition-entry-stage
   #:pipeline-definition-max-steps
   #:pipeline-definition-max-tool-iterations
   #:pipeline-definition-auto-approve-tools-p
   #:pipeline-context
   #:pipeline-context-definition
   #:pipeline-context-original-prompt
   #:pipeline-context-buffer
   #:pipeline-context-stage-results
   #:pipeline-stage-result
   #:pipeline-stage-result-stage-name
   #:pipeline-stage-result-prompt
   #:pipeline-stage-result-result
   #:pipeline-stage-result-parsed-output
   #:pipeline-stage-result-status
   #:pipeline-stage-result-error
   #:pipeline-stage-result-started-at
   #:pipeline-stage-result-finished-at
   #:pipeline-stage-result-final-text
   #:pipeline-stage-result-succeeded-p
   #:pipeline-run-result
   #:pipeline-run-result-pipeline-name
   #:pipeline-run-result-original-prompt
   #:pipeline-run-result-stage-results
   #:pipeline-run-result-final-stage-result
   #:pipeline-run-result-status
   #:pipeline-run-result-error
   #:pipeline-run-result-final-text
   #:define-pipeline
   #:defpipeline
   #:register-pipeline-definition
   #:find-pipeline-definition
   #:list-pipeline-definitions
   #:pipeline-test-profile
   #:pipeline-test-profile-name
   #:pipeline-test-profile-description
   #:pipeline-test-profile-command
   #:normalize-pipeline-test-profile-name
   #:define-pipeline-test-profile
   #:register-pipeline-test-profile
   #:find-pipeline-test-profile
   #:list-pipeline-test-profiles
   #:pipeline-last-stage-result
   #:pipeline-stage-output
   #:pipeline-stage-parsed-output
   #:run-pipeline-test-profiles
   #:run-pipeline-on-buffer
   #:run-pipeline-prompt
   #:run-pipeline-for-buffer
   #:buffer-has-active-pipeline-p
   #:run-subagent
   #:run-subagent-async
   #:*prompt-max-tool-iterations*
   #:*default-subagent-name*
   #:subagent-handle
   #:subagent-handle-id
   #:subagent-handle-prompt
   #:subagent-handle-agent-name
   #:subagent-handle-status
   #:subagent-handle-result
   #:subagent-handle-error
   #:subagent-handle-started-at
   #:subagent-handle-finished-at
   #:subagent-handle-thread
   #:subagent-handle-cancel-requested-p
   #:find-subagent
   #:list-subagents
   #:subagent-status
   #:subagent-done-p
   #:subagent-result
   #:subagent-error
   #:subagent-snapshot
   #:wait-subagent
   #:cancel-subagent
   #:prompt-run-result
   #:prompt-run-result-prompt
   #:prompt-run-result-final-text
   #:prompt-run-result-tool-events
   #:prompt-run-result-reasoning-blocks
   #:prompt-run-result-agent-name
   #:prompt-run-result-provider
   #:prompt-run-result-model
   #:prompt-run-result-think-level
   #:prompt-run-result-iterations
   #:prompt-run-result-stop-reason
   #:prompt-run-result-usage
   #:prompt-run-error
   #:prompt-run-error-message
   #:prompt-run-error-tool-events
   #:prompt-run-error-iterations
   #:prompt-run-error-provider
   #:prompt-run-error-model
   #:prompt-run-error-think-level
   #:prompt-tool-event
   #:prompt-tool-event-id
   #:prompt-tool-event-name
   #:prompt-tool-event-input
   #:prompt-tool-event-result-text
   #:prompt-tool-event-display
   #:prompt-tool-event-denied-p
   #:prompt-run-tool-names
   #:prompt-run-tool-count
   #:prompt-run-used-tool-p
   #:send-to-agent-with-context
   #:stop-streaming-response
   #:stop-llm-command
   #:switch-buffer-to-agent
    #:scroll-up-command
    #:scroll-down-command
    #:*scroll-page-size*))
